import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { FileText } from "lucide-react"

export default function AlertsLogsPage() {
  return (
    <div className="p-6 space-y-6">
      <div className="flex items-center gap-2">
        <h1 className="text-3xl font-bold tracking-tight">Alert Logs</h1>
        <FileText className="h-6 w-6 text-amber-500" />
      </div>
      <p className="text-muted-foreground">View historical alert logs and records</p>

      <Card>
        <CardHeader>
          <CardTitle>Alert History</CardTitle>
          <CardDescription>Historical record of system alerts</CardDescription>
        </CardHeader>
        <CardContent>
          <p>This page displays a historical log of all alerts generated by your system.</p>
        </CardContent>
      </Card>
    </div>
  )
}
